### ISSUE TITLE
Project does not compile

### ISSUE THREAD

**Issue by frogstack** [baiganovm/product-matching#1]
Hi, this is Graeme from Sortable.

When I follow your instructions, Maven fails to compile the code. I get the following error repeated quite a few times:

> `[ERROR] /home/graeme/hiring/Mikhail_Baiganov/product-matching/src/main/java/com/bmv/matching/factory/ProductFactory.java:[8,54] error: generics are not supported in -source 1.3`
> `[ERROR]`
> `[ERROR] (use -source 5 or higher to enable generics)`

Could you take a look at this?

**Comment by baiganovm** [comment]
Hi Graeme,
Thank you for posted issue.
I've just added source and target java version in pom.xml

Could you please try compile project again. It should be work now.

Thank you,
Mike
